// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFKKYN4kl-BREDA6o3jHB0Z3eXWpRoF8',
    appId: '1:428616323387:web:19f745334856792eb8a71e',
    messagingSenderId: '428616323387',
    projectId: 'facebook-app-9b5b3',
    authDomain: 'facebook-app-9b5b3.firebaseapp.com',
    storageBucket: 'facebook-app-9b5b3.appspot.com',
    measurementId: 'G-0VGP4S5KH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs_-WRGWd8XjdGb5Qc0Msy6qmoPNGzMrM',
    appId: '1:428616323387:android:424ffb4c87e5990cb8a71e',
    messagingSenderId: '428616323387',
    projectId: 'facebook-app-9b5b3',
    storageBucket: 'facebook-app-9b5b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmTMnkxpAoH-y3fEN-F_ZDCQeNPaklag0',
    appId: '1:428616323387:ios:49a5497940aa3080b8a71e',
    messagingSenderId: '428616323387',
    projectId: 'facebook-app-9b5b3',
    storageBucket: 'facebook-app-9b5b3.appspot.com',
    iosClientId: '428616323387-7v2ka0np03msh6vdlogrisoeuqng0q2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmTMnkxpAoH-y3fEN-F_ZDCQeNPaklag0',
    appId: '1:428616323387:ios:49a5497940aa3080b8a71e',
    messagingSenderId: '428616323387',
    projectId: 'facebook-app-9b5b3',
    storageBucket: 'facebook-app-9b5b3.appspot.com',
    iosClientId: '428616323387-7v2ka0np03msh6vdlogrisoeuqng0q2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookApp',
  );
}
